//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAEmailSenderMonthly
{
    using System;
    using System.Collections.Generic;
    
    public partial class bil_MonthlySettlementCutOff
    {
        public int merchant_id { get; set; }
        public byte smonth { get; set; }
        public short syear { get; set; }
        public int InternalCompanyID { get; set; }
        public int CorporateID { get; set; }
        public int AcquirerID { get; set; }
        public decimal MonthOpeningBalance { get; set; }
        public decimal MonthClosingBalance { get; set; }
        public decimal Total_CurrentBalance { get; set; }
        public decimal Total_Transaction_GrossAmount { get; set; }
        public decimal Total_Transaction_MerchantMDRAmount { get; set; }
        public decimal Total_Transaction_MerchantVATAmount { get; set; }
        public decimal Total_Transaction_MerchantWHTAmount { get; set; }
        public decimal Total_Transaction_MerchantMDRWHTAmount { get; set; }
        public decimal Total_Transaction_BankMDRAmount { get; set; }
        public decimal Total_Transaction_BankVATAmount { get; set; }
        public decimal Total_Transaction_BankWHTAmount { get; set; }
        public decimal Total_Transaction_BankMDRWHTAmount { get; set; }
        public decimal Total_Transaction_BankGrossAmountReceivable { get; set; }
        public decimal Total_Transaction_BankGrossAmountReceivableWHTAmount { get; set; }
        public decimal Total_Transaction_BankNetAmountReceivable { get; set; }
        public decimal Total_Transaction_NetAmount { get; set; }
        public decimal Total_Chargeback_GrossAmount { get; set; }
        public decimal Total_Chargeback_MerchantMDRAmount { get; set; }
        public decimal Total_Chargeback_MerchantVATAmount { get; set; }
        public decimal Total_Chargeback_MerchantWHTAmount { get; set; }
        public decimal Total_Chargeback_MerchantMDRWHTAmount { get; set; }
        public decimal Total_Chargeback_BankMDRAmount { get; set; }
        public decimal Total_Chargeback_BankVATAmount { get; set; }
        public decimal Total_Chargeback_BankWHTAmount { get; set; }
        public decimal Total_Chargeback_BankMDRWHTAmount { get; set; }
        public decimal Total_Chargeback_BankGrossAmountReceivable { get; set; }
        public decimal Total_Chargeback_BankGrossAmountReceivableWHTAmount { get; set; }
        public decimal Total_Chargeback_BankNetAmountReceivable { get; set; }
        public decimal Total_Chargeback_NetAmount { get; set; }
        public decimal Total_Refund_GrossAmount { get; set; }
        public decimal Total_Refund_MerchantMDRAmount { get; set; }
        public decimal Total_Refund_MerchantVATAmount { get; set; }
        public decimal Total_Refund_MerchantWHTAmount { get; set; }
        public decimal Total_Refund_MerchantMDRWHTAmount { get; set; }
        public decimal Total_Refund_BankMDRAmount { get; set; }
        public decimal Total_Refund_BankVATAmount { get; set; }
        public decimal Total_Refund_BankWHTAmount { get; set; }
        public decimal Total_Refund_BankMDRWHTAmount { get; set; }
        public decimal Total_Refund_BankGrossAmountReceivable { get; set; }
        public Nullable<decimal> Total_Refund_BankGrossAmountReceivableWHTAmount { get; set; }
        public decimal Total_Refund_BankNetAmountReceivable { get; set; }
        public decimal Total_Refund_NetAmount { get; set; }
        public decimal Total_TransactionAdjustment_GrossAmount { get; set; }
        public decimal Total_TransactionAdjustment_MerchantMDRAmount { get; set; }
        public decimal Total_TransactionAdjustment_MerchantVATAmount { get; set; }
        public decimal Total_TransactionAdjustment_MerchantWHTAmount { get; set; }
        public decimal Total_TransactionAdjustment_MerchantMDRWHTAmount { get; set; }
        public decimal Total_TransactionAdjustment_BankMDRAmount { get; set; }
        public decimal Total_TransactionAdjustment_BankVATAmount { get; set; }
        public decimal Total_TransactionAdjustment_BankWHTAmount { get; set; }
        public decimal Total_TransactionAdjustment_BankMDRWHTAmount { get; set; }
        public decimal Total_TransactionAdjustment_BankGrossAmountReceivable { get; set; }
        public decimal Total_TransactionAdjustment_BankGrossAmountReceivableWHTAmount { get; set; }
        public decimal Total_TransactionAdjustment_BankNetAmountReceivable { get; set; }
        public decimal Total_TransactionAdjustment_NetAmount { get; set; }
        public decimal Total_AdjustmentAmount { get; set; }
        public decimal Total_AmountPaid { get; set; }
        public decimal Total_RemainingBalance { get; set; }
        public decimal Total_Fraud_GrossAmount { get; set; }
        public decimal Total_Fraud_MerchantMDRAmount { get; set; }
        public decimal Total_Fraud_MerchantVATAmount { get; set; }
        public decimal Total_Fraud_MerchantWHTAmount { get; set; }
        public decimal Total_Fraud_MerchantMDRWHTAmount { get; set; }
        public decimal Total_Fraud_BankMDRAmount { get; set; }
        public decimal Total_Fraud_BankVATAmount { get; set; }
        public decimal Total_Fraud_BankWHTAmount { get; set; }
        public decimal Total_Fraud_BankMDRWHTAmount { get; set; }
        public decimal Total_Fraud_BankGrossAmountReceivable { get; set; }
        public decimal Total_Fraud_BankGrossAmountReceivableWHTAmount { get; set; }
        public decimal Total_Fraud_BankNetAmountReceivable { get; set; }
        public decimal Total_Fraud_NetAmount { get; set; }
        public decimal Total_FraudRelease_GrossAmount { get; set; }
        public decimal Total_FraudRelease_MerchantMDRAmount { get; set; }
        public decimal Total_FraudRelease_MerchantVATAmount { get; set; }
        public decimal Total_FraudRelease_MerchantWHTAmount { get; set; }
        public decimal Total_FraudRelease_MerchantMDRWHTAmount { get; set; }
        public decimal Total_FraudRelease_BankMDRAmount { get; set; }
        public decimal Total_FraudRelease_BankVATAmount { get; set; }
        public decimal Total_FraudRelease_BankWHTAmount { get; set; }
        public decimal Total_FraudRelease_BankMDRWHTAmount { get; set; }
        public decimal Total_FraudRelease_BankGrossAmountReceivable { get; set; }
        public decimal Total_FraudRelease_BankGrossAmountReceivableWHTAmount { get; set; }
        public decimal Total_FraudRelease_BankNetAmountReceivable { get; set; }
        public decimal Total_FraudRelease_NetAmount { get; set; }
        public byte Total_SettlementMovementFlag { get; set; }
        public byte Total_SOASendEmail { get; set; }
        public Nullable<int> DocID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
