//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAEmailSenderMonthly
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SOAMonthlyTransaction
    {
        public System.DateTime settlement_date { get; set; }
        public int MERCHANT_ID { get; set; }
        public string TRANSACTIONCODE { get; set; }
        public Nullable<decimal> txnAmount { get; set; }
        public Nullable<decimal> MDR { get; set; }
        public Nullable<decimal> GST { get; set; }
        public Nullable<decimal> AmountSectionA { get; set; }
        public Nullable<decimal> AmountSectionB { get; set; }
        public string COUNTRY { get; set; }
    }
}
