//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAEmailSenderMonthly
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class M3Entities : DbContext
    {
        public M3Entities()
            : base("name=M3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<bil_SettlementCutOff> bil_SettlementCutOff { get; set; }
        public DbSet<m3_EmailAttachment> m3_EmailAttachment { get; set; }
        public DbSet<m3_EmailRecipient> m3_EmailRecipient { get; set; }
        public DbSet<m3_EmailSender> m3_EmailSender { get; set; }
        public DbSet<m3_merchant> m3_merchant { get; set; }
        public DbSet<vw_MerchantFirstContact> vw_MerchantFirstContact { get; set; }
        public DbSet<vw_SOAMonthlyHeaders> vw_SOAMonthlyHeaders { get; set; }
        public DbSet<vw_SOAMonthlyTransaction> vw_SOAMonthlyTransaction { get; set; }
        public DbSet<bil_MonthlySettlementCutOff> bil_MonthlySettlementCutOff { get; set; }
    }
}
